export type IvaRetention = {
  id: string;
  receiptId: string;
  supplierId: string;
  branchId: string;
  period: string;
  voucherNumber: string;
  agentRif: string;
  supplierRif: string;
  supplierBusinessName: string | null;
  fiscalDocType: string;
  invoiceNumber: string | null;
  controlNumber: string | null;
  invoiceDate: string | null;
  affectedDocNumber: string | null;
  currency: string;
  exchangeRate: number | string | null;
  totalUsd: number | string;
  totalBs: number | string;
  baseImponibleUsd: number | string;
  baseImponibleBs: number | string;
  exemptUsd: number | string;
  exemptBs: number | string;
  vatUsd: number | string;
  vatBs: number | string;
  vatRate: number | string;
  retentionPct: number | string;
  vatRetainedUsd: number | string;
  vatRetainedBs: number | string;
  status: 'active' | 'voided';
  createdAt: string;
};
